######################################################################
# Automatically generated by qmake (2.01a) Mon Jun 23 10:07:33 2008
######################################################################

DEFINES += MAJOR_VERSION=0 MINOR_VERSION=5

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

CONFIG += qt debug
CONFIG -= app_bundle
QT += webkit network 

# Input
HEADERS += wkhtmltopdf.hh
SOURCES += wkhtmltopdf.cc
