---
# file: setup/tasks/debug.yml
#
# debug tasks.
#

- debug:
    var="{{ item }}"
  when: "{{ item }} is defined"
  with_items:
    - ansible_os_family
    - ansible_distribution
    - ansible_distribution_major_version
    - ansible_distribution_release
