#!/bin/bash

qmake wkhtmltopdf.pro -spec macx-g++

make src/image/Makefile
make src/pdf/Makefile
make src/lib/Makefile

for makefile in `find . -name Makefile`
do
  echo "update: $makefile"
  tmp=make.$$
  cat $makefile | sed -e 's/i386/x86_64/g' > $tmp
  mv $tmp $makefile
done

cd src/lib && make staticlib
cd -

echo "build examples"
tmp=make.$$
cat examples/Makefile | sed -e 's/-L ..\/bin -lwkhtmltox/..\/bin\/libwkhtmltox.a -lstdc++ -framework QtWebkit -framework QtSvg -framework QtXmlPatterns -framework QtGui -framework QtCore -framework QtNetwork/g' > $tmp
mv $tmp examples/Makefile
cd examples && make
cd -
